# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
# jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
# twitter:
#   username: DavidDarnes # jekyll-seo-tag > Owners twitter username
# author: DavidDarnes # jekyll-seo-tag > default author
# social: # jekyll-seo-tag > social overrides
#   name: David Darnes # jekyll-seo-tag > real name
#   links:  # jekyll-seo-tag > social aliases (sameAs)
#     - https://twitter.com/DavidDarnes
#     - https://www.facebook.com/daviddarnes
#     - https://www.linkedin.com/in/daviddarnes
#     - https://github.com/daviddarnes
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Africa/South_Africa # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Blog Posts # Needed for Siteleaf
    output: true
    description: "A collection of articles, ideas and stories from the Bulungula Tech Centre." # The post list page content
    feature_text: |
    feature_image: "/assets/images/blog/wave.png"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Bulungula Tech Centre" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.jpeg" # Site logo, also used in jekyll-seo-tag
description: "A scale-able, low-cost tech centre built with Raspberry Pis and free, open-source software" # Site description and default description, also used in jekyll-seo-tag
url: "https://bulungula-tech-centre.github.io/" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/bulungula-tech-centre/bulungula-tech-centre.github.io"
email: "bulungula.tech@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  192: '/assets/logos/logo@192px.png'
  512: '/assets/logos/logo@512px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Setup Guide
  url: /setup/
- title: Finances
  url: /finances/
- title: Blog
  url: /blog/
- title: Our Story
  url: /story/
- title: The Team
  url: /team/
- title: Contact us
  url: /contact/

navigation_footer:
- title: Bulungula Incubator
  url: https://bulungulaincubator.org/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Facebook: https://www.facebook.com/BulungulaIncubator/
  LinkedIn: https://www.linkedin.com/in/bulungula-incubator-02baa11b8/
  GitHub: https://github.com/bulungula-tech-centre/
  link: https://bulungulaincubator.org/

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap


guide_categories:
  - Setting up the Client Pis
  - Setting up the local network
  - Setting up the Server
  - Optional Extras
  - Reporting Issues
